# Generated by Django 3.1.1 on 2020-10-07 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0003_auto_20201007_0237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_text',
            new_name='post_input_text',
        ),
    ]
