# Generated by Django 3.1.1 on 2020-10-07 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0004_auto_20201007_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_bio',
            new_name='bio_input_text',
        ),
    ]
