# Generated by Django 3.1.1 on 2020-10-07 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0005_auto_20201007_0737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_picture',
            new_name='profile_picture',
        ),
    ]
