# Generated by Django 3.1.1 on 2020-10-15 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialnetwork', '0006_auto_20201007_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_input_text', models.CharField(max_length=200)),
                ('comment_time', models.DateTimeField()),
                ('comment_author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('comment_post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='socialnetwork.post')),
            ],
        ),
    ]
